// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['main']['App']['Close']();
}

export function GetTitle() {
  return window['go']['main']['App']['GetTitle']();
}

export function Minimize() {
  return window['go']['main']['App']['Minimize']();
}
